# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pullminder < Formula
  desc "Pullminder CLI — manage custom rule registries"
  homepage "https://pullminder.com"
  version "0.1.8"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pullminder/cli/releases/download/v0.1.8/pullminder-darwin-amd64"
      sha256 "72b5b90c73c25f1675bd25b77dd519c1a6bedc7ca9b4544e0dbd9e180b8aaf18"

      define_method(:install) do
        bin.install "pullminder-darwin-amd64" => "pullminder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pullminder/cli/releases/download/v0.1.8/pullminder-darwin-arm64"
      sha256 "1c3cb84e11ac1af868b1efaeb9206a804605280454cc5e0b77f412719c374e82"

      define_method(:install) do
        bin.install "pullminder-darwin-arm64" => "pullminder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pullminder/cli/releases/download/v0.1.8/pullminder-linux-amd64"
      sha256 "173233b6e19488312d1e6ea35ef8de524cae1f245f3f50e1afc6bd5e25f48704"
      define_method(:install) do
        bin.install "pullminder-linux-amd64" => "pullminder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pullminder/cli/releases/download/v0.1.8/pullminder-linux-arm64"
      sha256 "3da2be5c236565c370f5e8a30e3eedc4431951f23cb92121209c2120b6e1fc4e"
      define_method(:install) do
        bin.install "pullminder-linux-arm64" => "pullminder"
      end
    end
  end

  test do
    system "#{bin}/pullminder", "version"
  end
end
